name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    # Update to use the maintained ruby/setup-ruby
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0' # or the latest version supported

    - name: Install CocoaPods
      run: gem install cocoapods

    - name: Install dependencies
      run: pod install

    - name: Build
      run: xcodebuild -workspace MrLinux.xcworkspace -scheme YourSchemeName -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=latest' build
